var a = object_index
if (instance_number(a) > 1) {
	var _first = instance_find(a, 0);
	if (id != _first) {
		instance_destroy(); 
		exit; 
	}
}
global.cheat_disable = false
global.has_cheats_on = false
detach = 0
global.speedrun_timer = 0
depth = -300
shakex_mag = 0
shakex_mag_acc = 2
shakex_mag_maxdelay = 5
shakex_mag_delay = 0
shake_dirx = 1
detachedby = -1
follow_golf = 0
targetgolf = -4
camzoom = 1
max_zoom = 100
targetzoom = 1
lap_face_index = 0
zoomspd = 0.01
lastcollect = -1
camshake_queue = ds_queue_create()
panicshake = 0;
panicshakeacc = 0;		
color_array = array_create(1, 0)
collect_shake = 0
combobubblevisible = 1
previousrank = 0
rank_scale = 1
original_cam_width = 960
original_cam_height = 540
coop_zoom_width = ((original_cam_width / 4) * 1.5)
coop_zoom_height = ((original_cam_height / 4) * 1.5)
hud_posY = 0
pizzascore_index = 0
pizzascore_number = sprite_get_number(spr_pizzascore)
n = 0
image_speed = 0.35
alarm[1] = -1
global.seconds = 59
global.minutes = 0
global.miniboss = false
angle = 0
anglespd = 1
sin_a = 0
tgt_angle = 0
maxanglespd = 1
frame = 0
global.pizza = 0
global.pizzameter = 0
global.pillarhunger = 4000
basement = 0
shake_mag = 0
shake_mag_acc = 0
zoom = 0
chargecamera = 0
chargecamera_y = 0
alpha = 1
zoomh = 540
zoomw = 960
global.panicbg = 1
global.maxwave = 0
global.wave = 0
ded = 0
player = obj_player1
spr_player = -4
spr_speedbarHUD = -4
spr_speedbar_index = spr_plug
shoving = 0
bang = 0
image_speed = 0.35
p2pdistance = 0
p2pdistancex = 0
bound_camera = 0
global.timedgate = 0
healthshake = 0
healthold = 8
healthshaketime = 0
playerhealthup = 0
