wave = [
[1, states.arena_rand, [obj_cheeseslime, obj_forknight, obj_swedishmonkey, obj_minijohn]],
[2, states.arena_rand, [obj_cheeseslime, obj_forknight, obj_pepgoblin, obj_minijohn]],
[3, states.arena_rand, [obj_cheeseslime, obj_pizzagoblin, obj_fencer, obj_forknight, obj_pepgoblin]],
[4, states.arena_rand, [obj_cheeseslime, obj_forknight, obj_fencer, obj_ancho, obj_pepgoblin]],
[5, states.arena_rand, [obj_ancho, obj_forknight, obj_swedishmonkey, obj_pepgoblin, obj_minijohn]],
[6, states.arena_rand, [obj_indiancheese, obj_kentukykenny]],
[7, states.arena_rand, [obj_indiancheese, obj_minijohn, obj_ghoul]],
[8, states.arena_rand, [obj_farmerbaddie, obj_farmerbaddie2, obj_ghoul, obj_rancher, obj_banditochicken]],
[9, states.arena_rand, [obj_rancher, obj_badrat, obj_rancher, obj_badrat]],
[10, states.arena_rand, [obj_rancher, obj_kentukykenny, obj_badrat, obj_ghoul, obj_farmerbaddie]],
[11, states.arena_rand, [obj_canongoblin, obj_coolpineapple, obj_spitcheese]],
[12, states.arena_rand, [obj_pickle, obj_spitcheese, obj_noisegoblin]],
[13, states.arena_rand, [obj_miniufo, obj_miniufo_grounded, obj_noisey, obj_noisegoblin]],
[14, states.arena_rand, [obj_golfburger, obj_golfdemon]],
[15, states.arena_rand, [obj_canongoblin, obj_pickle, obj_miniufo, obj_golfdemon]],
[16, states.arena_rand, [obj_smokingpizzaslice, obj_thug_red, obj_thug_blue]],
[17, states.arena_rand, [obj_smokingpizzaslice, obj_pizzagoblin, obj_robot, obj_sausageman]],
[18, states.arena_rand, [obj_ninja, obj_swedishmonkey, obj_smokingpizzaslice, obj_badrat]],
[19, states.arena_rand, [obj_snowman, obj_pizzice]],
[20, states.arena_rand, [obj_robot, obj_ninja, obj_snowman]],
[21, states.arena_rand, [obj_badrat, obj_pizzard, obj_forknight]],
[22, states.arena_rand, [obj_ghost, obj_peppinoclone, obj_forknight]],
[23, states.arena_rand, [obj_patroller, obj_pizzard, obj_forknight, obj_minijohn]],
[24, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_bazookabaddie, obj_minijohn]],
[25, states.arena_rand, [obj_pizzard, obj_ghost, obj_peppinoclone, obj_soldier, obj_kentukybomber]],
]