visible = false
dialog = [
create_dialogue("GRRR I HATE NI-"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
create_dialogue("winter lodge"),
]