wave = [
[1, states.arena_all, [obj_badrat]],
[2, states.arena_rand, [obj_badrat, obj_clownmato]],
[3, states.arena_rand, [obj_badrat, obj_ghoul, obj_clownmato]],
[4, states.arena_rand, [obj_badrat, obj_ghost, obj_ghoul]],
[5, states.arena_all, [obj_soldier]],
[6, states.arena_rand, [obj_soldier, obj_badrat]],
[7, states.arena_rand, [obj_soldier, obj_badrat, obj_clownmato]],
[8, states.arena_rand, [obj_soldier, obj_ghost, obj_ghoul]],
[9, states.arena_rand, [obj_soldier, obj_ghost, obj_ghoul, obj_badrat]],
[10, states.arena_all, [obj_soldier, obj_kentukybomber, obj_patroller]],
[11, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_clownmato, obj_patroller]],
[12, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_ghoul, obj_ghost, obj_patroller]],
[13, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_ghoul, obj_ghost, obj_badrat, obj_patroller]],
[14, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_ghoul, obj_ghost, obj_patroller, obj_badrat, obj_pizzard]],
[15, states.arena_all, [obj_soldier, obj_kentukybomber, obj_patroller, obj_bazookabaddie]],
[16, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_bazookabaddie, obj_pizzard, obj_forknight]],
[17, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_bazookabaddie, obj_ghost, obj_peasanto]],
[18, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_patroller, obj_bazookabaddie, obj_clownmato, obj_ghoul]],
[19, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_bazookabaddie, obj_pizzard, obj_ghost, obj_peasanto, obj_badrat]],
[20, states.arena_all, [obj_bazookabaddie, obj_bazookabaddie, obj_patroller, obj_bazookabaddie]],
[21, states.arena_rand, [obj_soldier, obj_kentukybomber, obj_bazookabaddie, obj_clownmato, obj_pizzard, obj_badrat, obj_ghost]],
]